### ISSUE TITLE
Update Photo - About page

### ISSUE THREAD

**Issue by mvincent164** [TheFuturesFund/walls-site#24]
![capture](https://user-images.githubusercontent.com/43098038/52905299-f77a8700-31fd-11e9-8cef-ac99b2309f17.PNG)

**Comment by JorrenBell** [comment]
![Screen Shot 2019-03-23 at 2 21 17 PM](https://user-images.githubusercontent.com/38590719/54870628-2f359b00-4d77-11e9-8e06-cf0c0d887a49.png)
@mvincent164
